
name: mariadb

services:
  mariadb-server:
    image: mariadb:10.5
    container_name: mariadb
    restart: unless-stopped
    security_opt:
      - seccomp:unconfined
      - apparmor:unconfined
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - MYSQL_ROOT_PASSWORD=${ROOT_PASSWD}
      - DB_TYPE=mariadb
      - DB_HOST=localhost
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWD=${ROOT_PASSWD}
      - LOG_LEVEL=INFO
      - LOG_FILE=/logs/sql.log
      - HASH_FILE=/logs/sql-hashes.db
    volumes:
      - ${USER_DIR}/mariadb/data:/var/lib/mysql
      - ${USER_DIR}/mariadb/config:/etc/mysql/conf.d
      - ${USER_DIR}/mariadb/log:/logs
      - ${WATCH_SCRIPT}:/opt/scripts/sql-watcher.sh
      - ${WATCH_DIR:-./etc/sql}:/docker-entrypoint-initdb.d:ro
    env_file:
      - .env
    ports:
      - '3306:3306'
    networks:
      - local_network
    command: >
      sh -c "
      if [ -f \"$$WATCH_SQL_SCRIPT\" ]; then
          chmod +x \"$$WATCH_SQL_SCRIPT\"
          \"$$WATCH_SQL_SCRIPT\" &
      fi
      
      exec /usr/local/bin/docker-entrypoint.sh mysqld \
        --transaction-isolation=READ-COMMITTED \
        --character-set-server=utf8mb4 \
        --collation-server=utf8mb4_unicode_ci \
        --max-connections=512 \
        --innodb-rollback-on-timeout=OFF \
        --innodb-lock-wait-timeout=50 \
        --innodb_buffer_pool_size=512M \
        --innodb_log_file_size=512M
      "
networks:
  local_network:
    external: true