name: duplicati

services:
  duplicati:
    container_name: duplicati
    image: lscr.io/linuxserver/duplicati:latest
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - CLI_ARGS= --log-level=verbose --webservice-log-level=verbose
      - DUPLICATI__WEBSERVICE_PASSWORD=${WEB_PASSWD_KEY}
      - SETTINGS_ENCRYPTION_KEY=${DB_PASSWD_KEY}
    volumes:
      - ${CONFIG_PATH}:/config
      - ${BACKUP_PATH}:/backups
      - ${SOURCE_PATH}:/source
      - type: bind
        source: ${USR_PATH}
        target: /source/usr
        read_only: true
    env_file:
      - .env
    ports:
      - 8200:8200
    privileged: true
    hostname: duplicati  
    restart: unless-stopped
    network_mode: bridge