
name: portainer

services:
  portainer-server:
    container_name: portainer
    image: 6053537/portainer-ce     # 6053537
    command: -H unix:///var/run/docker.sock
    environment:
      - TZ=Asia/Shanghai
      - PORTAINER_ADMIN_PASSWORD=lysgwl3221
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /app/usr/portainer/data:/data
      #- portainer_data:/data
    ports:
      - "9000:9000"
    privileged: true	# 授予容器更高的权限
    hostname: portainer
    restart: always
    networks:
      - local_network
     
networks:
  local_network:
    external: true