
services:
  db:
    container_name: mariadb-database
    image: mariadb:10.6
    command: --transaction-isolation=READ-COMMITTED --log-bin=binlog --binlog-format=ROW
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWD}
      MYSQL_USER: ${DB_USER_NAME}
      MYSQL_PASSWORD: ${DB_USER_PASSWD}
      MYSQL_DATABASE: ${DB_DATA_BASE}
      TZ: ${TZ}
    volumes:
      - ${DB_PATH}:/var/lib/mysql
    restart: always
    networks:
      - local_network

  redis:
    container_name: redis-dbcache
    image: redis:alpine
    restart: always
    networks:
      - local_network

  app:
    container_name: nextcloud
    image: nextcloud:stable-apache
    environment:
      - MYSQL_DATABASE=${DB_DATA_BASE}
      - MYSQL_USER=${DB_USER_NAME}
      - MYSQL_PASSWORD=${DB_USER_PASSWD}
      - MYSQL_HOST=db
      - REDIS_HOST=redis
      - TZ=${TZ}
    volumes:
      - ${NEXTCLOUD_PATH}/data:/var/www/html
      - ${NEXTCLOUD_PATH}/config:/var/www/html/config
      - ${NEXTCLOUD_PATH}/apps:/var/www/html/apps
      - ${NEXTCLOUD_PATH}/themes:/var/www/html/themes
    ports:
      - "8000:80"  
    depends_on:
      - db
      - redis
    restart: always  
    networks:
      - local_network
      
  onlyoffice:
    container_name: onlyoffice
    image: onlyoffice/documentserver
    environment:
      JWT_ENABLED: 'true'
      JWT_SECRET:
      TZ: ${TZ}
    restart: always
    networks:
      - local_network

networks:
  local_network:
    external: true 