
name: duplicati

x-defaults: &defaults
  BACKUP_PATH: /app/usr/duplicati
  
services:
  duplicati-server:
    container_name: duplicati
    image: lscr.io/linuxserver/duplicati:latest
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Shanghai
      - CLI_ARGS= --log-level=verbose --webservice-log-level=verbose
      - DUPLICATI__WEBSERVICE_PASSWORD=${WEB_PASSWD_KEY:-123456}
      - SETTINGS_ENCRYPTION_KEY=${ENCRYPTION_KEY:-12345678}
    volumes:
      - ${BACKUP_PATH}/config:/config
      - ${BACKUP_PATH}/backup:/backups
      - ${BACKUP_PATH}/source:/source
      - type: volume
        source: nas-files
        target: /source/usr
        read_only: true
    ports:
      - ${DUPLICATI_PORT:-8200}:8200
    privileged: true
    hostname: duplicati
    networks:
      - local_network
    restart: unless-stopped
    
networks:
  local_network:
    external: true
    
volumes:
  nas-files:
    external: true