---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/bookmarks

- 智能模型:
    - ChatGPT:
        - href: https://chatgpt.com/
    - Gemini:
        - href: https://gemini.google.com/
    - 当贝AI:
        - href: https://ai.dangbei.com/chat
    - 问小白:
        - href: https://www.wenxiaobai.com/
    - 腾讯元宝:
        - href: https://yuanbao.tencent.com/
    - 通义:
        - href: https://www.tongyi.com/
          
- 搜索引擎:
    - 百度:
        - href: https://reddit.com/
    - Bing:
        - href: https://cn.bing.com/
    - 360搜索:
        - href: https://www.so.com/
        
- Entertainment:
    - YouTube:
        - abbr: YT
          href: https://youtube.com/
- Entertainment:
    - YouTube:
        - abbr: YT
          href: https://youtube.com/
- Entertainment:
    - YouTube:
        - abbr: YT
          href: https://youtube.com/
- Entertainment:
    - YouTube:
        - abbr: YT
          href: https://youtube.com/
- Entertainment:
    - YouTube:
        - abbr: YT
          href: https://youtube.com/
- Entertainment:
    - YouTube:
        - abbr: YT
          href: https://youtube.com/
- Entertainment:
    - YouTube:
        - abbr: YT
          href: https://youtube.com/
- Entertainment:
    - YouTube:
        - abbr: YT
          href: https://youtube.com/
- Entertainment:
    - YouTube:
        - abbr: YT
          href: https://youtube.com/
- Entertainment:
    - YouTube:
        - abbr: YT
          href: https://youtube.com/
- Entertainment:
    - YouTube:
        - abbr: YT
          href: https://youtube.com/
- Entertainment:
    - YouTube:
        - abbr: YT
          href: https://youtube.com/