
name: nginx

services:
  nginx-server:
    container_name: nginx
    image: nginx-image
    environment:
      - TZ=${TZ}
    volumes:
      - ${NGINX_PATH}/config:/config
      - ${NGINX_PATH}/data:/data
    env_file:
      - .env
    ports:
      - '80:80'
    hostname: nginx
    restart: unless-stopped
    networks:
      local_network: {}
      
networks:
  local_network:
    external: true