
name: jellyfin

services:
  jellyfin-server:
    container_name: jellyfin 
    image: nyanmisaka/jellyfin     # nyanmisaka/jellyfin | jellyfin/jellyfin | linuxserver/jellyfin
    devices:
      - /dev/dri:/dev/dri
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - HTTP_PROXY=${PROXY_HOST}
      - HTTPS_PROXY=${PROXY_HOST}
    volumes:
      - ${CONFIG_PATH}:/config
      - ${CACHE_PATH}:/cache
      - ${DATA_PATH}:/data
      - ${NGINXCFG_PATH}:/config/nginx
      - ${NGINXCFG_FILE}:/config/jellyfin.conf
      - nas-media:/media
    env_file:
      - .env
    ports:
      - 8096:8096
    privileged: true
    hostname: jellyfin
    networks:
      - local_network
    entrypoint: ["/bin/sh", "-c"]
    command: >
      '
        # 复制配置文件
        if [ -f "/config/jellyfin.conf" ] && [ -d "/config/nginx/extra/proxy-config" ]; then
            if [ ! -f "/config/nginx/extra/proxy-config/jellyfin.conf" ]; then
                cp -v "/config/jellyfin.conf" "/config/nginx/extra/proxy-config/"
            fi
        fi
        
        # 启动主进程
        exec /jellyfin/jellyfin
      '
    restart: always
      
networks:
  local_network:
    external: true
    
volumes:
  nas-media:
    external: true