
name: jellyfin

services:
  jellyfin-server:
    container_name: jellyfin 
    image: nyanmisaka/jellyfin     # nyanmisaka/jellyfin | jellyfin/jellyfin | linuxserver/jellyfin
    devices:
      - /dev/dri:/dev/dri
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - HTTP_PROXY=${PROXY_HOST}
      - HTTPS_PROXY=${PROXY_HOST}
    volumes:
      - ${CONFIG_PATH}:/config
      - ${CACHE_PATH}:/cache
      - ${DATA_PATH}:/data
      - ${MEDIA_PATH}:/media
      #- media_share:/media
    env_file:
      - .env
    ports:
      - 8096:8096
    privileged: true
    hostname: jellyfin
    restart: always
    #extra_hosts:
    #  - "api.themoviedb.org:31.13.85.34"
    #  - "api.themoviedb.org:128.121.146.235"
    networks:
      - local_network
      
networks:
  local_network:
    external: true