
name: filesync

services:
  filesync-server:
    container_name: filesync
    image: filesync-image
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - HTTP_PROXY=${PROXY_HOST}
      - HTTPS_PROXY=${PROXY_HOST}
    #cap_add:
    #  - SYS_ADMIN 
    #  - DAC_READ_SEARCH
    volumes:
      - ${FILESYNC_PATH}/config:/config
      - ${FILESYNC_PATH}/data:/data
      - ${FILESYNC_PATH}/usr:/mnt/usr
      - nas_files:/mnt/usr/files
      - nas_media:/mnt/usr/media
      - nas_project:/mnt/usr/project
    env_file:
      - .env
    ports:
      #- '8015:5244'
      #- '8016:8384'
      - '22000:22000/tcp'   # 文件传输端口映射（TCP）
      - '22000:22000/udp'   # 文件传输端口映射（UDP）
      - '21027:21027/udp'   # 设备发现端口映射（UDP）
    hostname: filesync
    networks:
      - local_network
    restart: unless-stopped  
      
  duplicati-server:
    container_name: duplicati
    image: lscr.io/linuxserver/duplicati:latest
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - CLI_ARGS= --log-level=verbose --webservice-log-level=verbose
      - DUPLICATI__WEBSERVICE_PASSWORD=${WEB_PASSWD_KEY}
      - SETTINGS_ENCRYPTION_KEY=${DB_PASSWD_KEY}
    volumes:
      - ${BACKUP_PATH}/config:/config
      - ${BACKUP_PATH}/backup:/backups
      - ${BACKUP_PATH}/source:/source
      - type: bind
        source: ${FILES_PATH}
        target: /source/usr
        read_only: true
    env_file:
      - .env
    ports:
      - 8200:8200
    privileged: true
    hostname: duplicati
    networks:
      - local_network
    restart: unless-stopped  
    
networks:
  local_network:
    external: true
    
volumes:
  nas_files:
    external: true
  nas_media:
    external: true
  nas_project:
    external: true