
name: filesync

services:
  filesync-server:
    container_name: filesync
    image: filesync-image
    environment:
      - TZ=${TZ}
    volumes:
      - ${CONFIG_PATH}:/config
      - ${DATA_PATH}:/data
      - ${USR_PATH}:/mnt/usr
      - ${FILES_PATH}:/mnt/usr/files
      - ${PROJECT_PATH}:/mnt/usr/project
    env_file:
      - .env
    ports:
      - '8022:8022'
      - '8080:8080'         # web页面端口
      - '22000:22000/tcp'   # 文件传输端口映射（TCP）
      - '22000:22000/udp'   # 文件传输端口映射（UDP）
      - '21027:21027/udp'   # 设备发现端口映射（UDP）
    hostname: filesync  
    restart: unless-stopped  
    network_mode: bridge    # bridge